/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Edison
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    public JDesktopPane getDskMenu() {
        return dskMenu;
    }

    public void setDskMenu(JDesktopPane dskMenu) {
        this.dskMenu = dskMenu;
    }

    public JMenu getMnSocios() {
        return mnSocios;
    }

    public void setMnSocios(JMenu mnSocios) {
        this.mnSocios = mnSocios;
    }

    public JMenuItem getMniSocios() {
        return mniSocios;
    }

    public void setMniSocios(JMenuItem mniSocios) {
        this.mniSocios = mniSocios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskMenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSocios = new javax.swing.JMenu();
        mniSocios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dskMenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dskMenuLayout = new javax.swing.GroupLayout(dskMenu);
        dskMenu.setLayout(dskMenuLayout);
        dskMenuLayout.setHorizontalGroup(
            dskMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        dskMenuLayout.setVerticalGroup(
            dskMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        mnSocios.setText("Socios");

        mniSocios.setText("Socios");
        mnSocios.add(mniSocios);

        jMenuBar1.add(mnSocios);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnSocios;
    private javax.swing.JMenuItem mniSocios;
    // End of variables declaration//GEN-END:variables
}
